basePath: /api/v1
info:
  contact: {}
  description: This is a sample todo-list server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Todo-List API
  version: "1.0"
paths: {}
swagger: "2.0"
